name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t <your-dockerhub-saikeerthi03>/nodejs-demo-app:latest .
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u <your-dockerhub-username> --password-stdin
      - name: Push Docker Image
        run: docker push <your-dockerhub-saikeerthi03>/nodejs-demo-app:latest
